/**
 * 3D Farm Asset Pack — voxel farm / codex / seed connections.
 *
 * Source: D:\Games\Models\3D Farm Asset Pack.fbx (Portuguese-named meshes).
 * Public: models/packs/farm_asset_pack_3d.glb
 * Catalog: content/worlds/farm-asset-pack-catalog.json
 *
 * Name map: cerca=fence · portao=gate · feno=hay · cenoura=carrot · trigo=wheat
 * · telhas=roof tile · arvore=tree · galinha=chicken · flor=flower
 */
import * as THREE from "three";
import { loadGltfFirst } from "../assets";
import { sharedGltfLoader } from "../loaders/gltf";
import type { BlockTypeId } from "@workspace/voxel-canonical";
import type { BlockData } from "./types";

export const FARM_ASSET_PACK_R2 = "models/packs/farm_asset_pack_3d.glb";
export const FARM_ASSET_PACK_PATHS = [
  FARM_ASSET_PACK_R2,
  "models/packs/farm_asset_pack_3d.glb",
] as const;

export type FarmAssetGroup =
  | "field"
  | "farm"
  | "crop"
  | "fence"
  | "structure"
  | "nature"
  | "animal"
  | "path"
  | "prop";

export interface FarmAssetPiece {
  meshIndex: number;
  name: string;
  role: string;
  group: FarmAssetGroup;
  use: string[];
  codexTerrain: BlockTypeId;
  codexHint?: string;
  seed?: boolean;
  building?: boolean;
  item?: boolean;
}

/**
 * Curated role defaults (meshIndex filled at load from name match).
 * Full numeric catalog is generated by scripts/export_farm_asset_pack.py.
 */
export const FARM_ASSET_ROLES: Record<
  string,
  { group: FarmAssetGroup; codexTerrain: BlockTypeId; seed?: boolean; building?: boolean; item?: boolean }
> = {
  fence: { group: "fence", codexTerrain: "log" },
  gate: { group: "structure", codexTerrain: "woodPlanks", building: true },
  hay: { group: "farm", codexTerrain: "brickYellow", seed: true, item: true },
  carrot: { group: "crop", codexTerrain: "leaves", seed: true, item: true },
  wheat: { group: "crop", codexTerrain: "leaves", seed: true, item: true },
  flower_blue: { group: "crop", codexTerrain: "leaves", seed: true, item: true },
  flower_white: { group: "crop", codexTerrain: "leaves", seed: true, item: true },
  flower_pink: { group: "crop", codexTerrain: "leaves", seed: true, item: true },
  tree: { group: "nature", codexTerrain: "log" },
  tree_conifer: { group: "nature", codexTerrain: "log" },
  roof_tile: { group: "structure", codexTerrain: "brickRed", building: true },
  chicken: { group: "animal", codexTerrain: "blockSquare", item: true },
  barn: { group: "structure", codexTerrain: "brickRed", building: true },
  shed: { group: "structure", codexTerrain: "woodPlanks", building: true },
  silo_post: { group: "structure", codexTerrain: "brickGrey", building: true },
  field_patch: { group: "field", codexTerrain: "dirt" },
  crate: { group: "prop", codexTerrain: "woodPlanks", item: true },
  barrel: { group: "prop", codexTerrain: "woodPlanks", item: true },
};

/** Seed item ids for bag / craft / plant ops. */
export const FARM_SEEDS = [
  {
    id: "seed_carrot",
    label: "Carrot Seed",
    cropRole: "carrot",
    growsInto: "item_carrot",
    codexTerrain: "leaves" as BlockTypeId,
    plantDays: 3,
  },
  {
    id: "seed_wheat",
    label: "Wheat Seed",
    cropRole: "wheat",
    growsInto: "item_wheat",
    codexTerrain: "leaves" as BlockTypeId,
    plantDays: 4,
  },
  {
    id: "seed_flower_blue",
    label: "Blue Flower Seed",
    cropRole: "flower_blue",
    growsInto: "item_flower_blue",
    codexTerrain: "leaves" as BlockTypeId,
    plantDays: 2,
  },
  {
    id: "seed_flower_white",
    label: "White Flower Seed",
    cropRole: "flower_white",
    growsInto: "item_flower_white",
    codexTerrain: "leaves" as BlockTypeId,
    plantDays: 2,
  },
  {
    id: "seed_flower_pink",
    label: "Pink Flower Seed",
    cropRole: "flower_pink",
    growsInto: "item_flower_pink",
    codexTerrain: "leaves" as BlockTypeId,
    plantDays: 2,
  },
  {
    id: "seed_hay_grass",
    label: "Hay Grass Seed",
    cropRole: "hay",
    growsInto: "item_hay",
    codexTerrain: "brickYellow" as BlockTypeId,
    plantDays: 2,
  },
] as const;

/** Building kit ids → preferred mesh roles from the pack. */
export const FARM_BUILDINGS = [
  { id: "bld_barn", label: "Farm Barn", role: "barn", codexTerrain: "brickRed" as BlockTypeId },
  { id: "bld_shed", label: "Farm Shed", role: "shed", codexTerrain: "woodPlanks" as BlockTypeId },
  { id: "bld_gate", label: "Farm Gate", role: "gate", codexTerrain: "woodPlanks" as BlockTypeId },
  { id: "bld_fence", label: "Farm Fence", role: "fence", codexTerrain: "log" as BlockTypeId },
  { id: "bld_silo", label: "Silo / Post", role: "silo_post", codexTerrain: "brickGrey" as BlockTypeId },
  { id: "bld_roof", label: "Roof Tiles", role: "roof_tile", codexTerrain: "brickRed" as BlockTypeId },
] as const;

let packRoot: THREE.Object3D | null = null;
let packMeshes: THREE.Mesh[] = [];
let pieceIndex: FarmAssetPiece[] = [];
let packLoad: Promise<void> | null = null;

export function classifyFarmMeshName(name: string): {
  role: string;
  group: FarmAssetGroup;
  codexTerrain: BlockTypeId;
  seed?: boolean;
  building?: boolean;
  item?: boolean;
} {
  const n = name.toLowerCase();
  if (n.includes("cerca")) return { role: "fence", ...FARM_ASSET_ROLES.fence };
  if (n.includes("portao")) return { role: "gate", ...FARM_ASSET_ROLES.gate };
  if (n.includes("feno")) return { role: "hay", ...FARM_ASSET_ROLES.hay };
  if (n.includes("cenoura")) return { role: "carrot", ...FARM_ASSET_ROLES.carrot };
  if (n.includes("trigo")) return { role: "wheat", ...FARM_ASSET_ROLES.wheat };
  if (n.includes("flor azul")) return { role: "flower_blue", ...FARM_ASSET_ROLES.flower_blue };
  if (n.includes("flor branca")) return { role: "flower_white", ...FARM_ASSET_ROLES.flower_white };
  if (n.includes("flor rosa")) return { role: "flower_pink", ...FARM_ASSET_ROLES.flower_pink };
  if (n.includes("arvore") || n.includes("árvore")) return { role: "tree", ...FARM_ASSET_ROLES.tree };
  if (n.includes("telhas")) return { role: "roof_tile", ...FARM_ASSET_ROLES.roof_tile };
  if (n.includes("galinha")) return { role: "chicken", ...FARM_ASSET_ROLES.chicken };
  if (n.startsWith("cone")) return { role: "tree_conifer", ...FARM_ASSET_ROLES.tree_conifer };
  if (n.startsWith("plane") || n.startsWith("circle")) return { role: "field_patch", ...FARM_ASSET_ROLES.field_patch };
  if (n.startsWith("cube")) return { role: "building_block", group: "structure", codexTerrain: "woodPlanks", building: true };
  if (n.startsWith("cylinder")) return { role: "column", group: "structure", codexTerrain: "woodPlanks", building: true };
  return { role: "misc", group: "prop", codexTerrain: "blockBlank" };
}

export async function ensureFarmAssetPackLoaded(): Promise<boolean> {
  if (packRoot && packMeshes.length) return true;
  if (!packLoad) {
    packLoad = (async () => {
      const { scene } = await loadGltfFirst([...FARM_ASSET_PACK_PATHS], sharedGltfLoader(), {
        prepMaterials: true,
      });
      packRoot = scene;
      const meshes: THREE.Mesh[] = [];
      scene.traverse((o) => {
        const m = o as THREE.Mesh;
        if (m.isMesh && m.geometry) meshes.push(m);
      });
      meshes.sort((a, b) => a.name.localeCompare(b.name));
      packMeshes = meshes;
      pieceIndex = meshes.map((m, i) => {
        const c = classifyFarmMeshName(m.name);
        return {
          meshIndex: i,
          name: m.name,
          role: c.role,
          group: c.group,
          use: [c.group, "farm"],
          codexTerrain: c.codexTerrain,
          seed: c.seed,
          building: c.building,
          item: c.item,
        };
      });
      console.info(
        `[farmAssetPack] loaded meshes=${packMeshes.length} crops=${pieceIndex.filter((p) => p.group === "crop").length}`,
      );
    })().catch((err) => {
      packLoad = null;
      console.warn("[farmAssetPack] load failed", err);
      throw err;
    });
  }
  try {
    await packLoad;
    return !!(packRoot && packMeshes.length);
  } catch {
    return false;
  }
}

export function getFarmAssetPieces(): readonly FarmAssetPiece[] {
  return pieceIndex;
}

export function farmPiecesByRole(role: string): FarmAssetPiece[] {
  return pieceIndex.filter((p) => p.role === role);
}

export function farmPiecesByGroup(group: FarmAssetGroup): FarmAssetPiece[] {
  return pieceIndex.filter((p) => p.group === group);
}

export async function extractFarmAssetPiece(
  meshIndex: number,
  targetHeight = 1.4,
): Promise<THREE.Group | null> {
  const ok = await ensureFarmAssetPackLoaded();
  if (!ok) return null;
  const src = packMeshes[meshIndex];
  if (!src) return null;
  const wrap = new THREE.Group();
  wrap.name = `farm3d:${src.name}`;
  wrap.userData.farmPiece = pieceIndex[meshIndex];
  wrap.add(src.clone(true));
  wrap.updateMatrixWorld(true);
  const box = new THREE.Box3().setFromObject(wrap);
  const size = new THREE.Vector3();
  box.getSize(size);
  const h = Math.max(size.y, 0.05);
  wrap.scale.setScalar(targetHeight / h);
  wrap.updateMatrixWorld(true);
  const box2 = new THREE.Box3().setFromObject(wrap);
  const c = box2.getCenter(new THREE.Vector3());
  wrap.position.x -= c.x;
  wrap.position.z -= c.z;
  wrap.position.y -= box2.min.y;
  return wrap;
}

export async function extractFarmAssetByRole(
  role: string,
  targetHeight = 1.4,
  variant = 0,
): Promise<THREE.Group | null> {
  const ok = await ensureFarmAssetPackLoaded();
  if (!ok) return null;
  const list = farmPiecesByRole(role);
  if (!list.length) return null;
  const piece = list[variant % list.length];
  return extractFarmAssetPiece(piece.meshIndex, targetHeight);
}

/**
 * Scatter farm accents on a voxel map: fences, crop rows, optional trees/hay.
 * Returns placed prop groups (caller adds to scene).
 */
export async function scatterFarmAssetProps(opts: {
  half?: number;
  cropRows?: number;
  fence?: boolean;
  trees?: boolean;
}): Promise<THREE.Group[]> {
  const half = opts.half ?? 12;
  const out: THREE.Group[] = [];
  const ok = await ensureFarmAssetPackLoaded();
  if (!ok) return out;

  if (opts.fence !== false) {
    // Perimeter fence
    const posts = farmPiecesByRole("fence");
    for (let i = 0; i < posts.length && i < 24; i++) {
      const g = await extractFarmAssetPiece(posts[i % posts.length].meshIndex, 1.2);
      if (!g) continue;
      const t = (i / 24) * Math.PI * 2;
      g.position.set(Math.cos(t) * half, 0, Math.sin(t) * half);
      g.rotation.y = -t + Math.PI / 2;
      out.push(g);
    }
  }

  const rows = opts.cropRows ?? 3;
  const crops = ["carrot", "wheat", "flower_blue"] as const;
  for (let r = 0; r < rows; r++) {
    const role = crops[r % crops.length];
    const list = farmPiecesByRole(role);
    if (!list.length) continue;
    for (let c = 0; c < 6; c++) {
      const g = await extractFarmAssetPiece(list[c % list.length].meshIndex, 0.7);
      if (!g) continue;
      g.position.set(-half * 0.4 + c * 1.1, 0, -half * 0.3 + r * 1.4);
      out.push(g);
    }
  }

  if (opts.trees) {
    const trees = farmPiecesByRole("tree");
    for (let i = 0; i < Math.min(4, trees.length); i++) {
      const g = await extractFarmAssetPiece(trees[i].meshIndex, 2.4);
      if (!g) continue;
      g.position.set(half * 0.55 * (i % 2 === 0 ? 1 : -1), 0, half * 0.4 - i * 0.8);
      out.push(g);
    }
  }

  return out;
}

/**
 * Build a simple codex-mapped farm plot as voxel blocks (tilled dirt + crop tops).
 */
export function buildFarmAssetBlocks(opts?: { half?: number }): BlockData[] {
  const half = opts?.half ?? 10;
  const blocks: BlockData[] = [];
  const cell = (x: number, y: number, z: number, type: BlockTypeId): BlockData => ({
    x,
    y,
    z,
    shape: "block",
    color: 0,
    rotation: 0,
    type,
  });
  // Field grass ring
  for (let x = -half; x <= half; x++) {
    for (let z = -half; z <= half; z++) {
      const edge = Math.abs(x) === half || Math.abs(z) === half;
      blocks.push(cell(x, 0, z, edge ? "log" : "grass"));
    }
  }
  // Tilled plots
  for (let x = -6; x <= 6; x++) {
    for (let z = -4; z <= 2; z++) {
      blocks.push(cell(x, 0, z, "dirt"));
      // Crop tops every other cell
      if ((x + z) % 2 === 0) {
        blocks.push(cell(x, 1, z, "leaves"));
      }
    }
  }
  // Barn pad
  for (let x = 7; x <= half - 1; x++) {
    for (let z = 4; z <= half - 1; z++) {
      blocks.push(cell(x, 0, z, "woodPlanks"));
    }
  }
  return blocks;
}

/** Codex connection table: role → Mine-Loader / voxel terrain. */
export function farmCodexBindings(): Array<{
  role: string;
  codexTerrain: BlockTypeId;
  seedId?: string;
  buildingId?: string;
}> {
  return [
    { role: "carrot", codexTerrain: "leaves", seedId: "seed_carrot" },
    { role: "wheat", codexTerrain: "leaves", seedId: "seed_wheat" },
    { role: "flower_blue", codexTerrain: "leaves", seedId: "seed_flower_blue" },
    { role: "flower_white", codexTerrain: "leaves", seedId: "seed_flower_white" },
    { role: "flower_pink", codexTerrain: "leaves", seedId: "seed_flower_pink" },
    { role: "hay", codexTerrain: "brickYellow", seedId: "seed_hay_grass" },
    { role: "fence", codexTerrain: "log", buildingId: "bld_fence" },
    { role: "gate", codexTerrain: "woodPlanks", buildingId: "bld_gate" },
    { role: "barn", codexTerrain: "brickRed", buildingId: "bld_barn" },
    { role: "shed", codexTerrain: "woodPlanks", buildingId: "bld_shed" },
    { role: "roof_tile", codexTerrain: "brickRed", buildingId: "bld_roof" },
    { role: "field_patch", codexTerrain: "dirt" },
    { role: "tree", codexTerrain: "log" },
  ];
}
