/**
 * Weapon → live baked anim pack (SSOT consumer of content/anims/weapon-live-packs.json).
 *
 * When a weapon is equipped, only that pack's loco/attack/skill roles (+ shared
 * traversal) should load. Integrity SHAs live in content/manifests/anims.integrity.json
 * (generated by `npm run anims:verify -- --write`).
 */

/** Keep in sync with content/anims/weapon-live-packs.json via anims:sync */
import weaponMapJson from "./data/weapon-live-packs.json";
import { animPackForWeapon, type AnimPack } from "../grudge/anims";

export type LiveRoleStatus = "ready" | "fallback" | "missing";

export interface WeaponLiveDef {
  label: string;
  animPack: string;
  fallbackPack: string | null;
  liveRoles: Record<string, string>;
  liveWhenIncomplete?: Record<string, string> & { note?: string };
  mixamoSources?: string[];
  skillSlots?: string[];
  inheritsFrom?: string;
}

type WeaponMapDoc = {
  version: number;
  policy: Record<string, unknown>;
  sharedTraversal: {
    pack: string;
    roles: Record<string, string>;
    alwaysLoadWithWeapon?: boolean;
  };
  roleContract: {
    required: string[];
    recommended?: string[];
    optional?: string[];
  };
  weapons: Record<string, Partial<WeaponLiveDef> & { inheritsFrom?: string }>;
};

const DOC = weaponMapJson as WeaponMapDoc;

function resolveEntry(weaponId: string, seen = new Set<string>()): WeaponLiveDef | null {
  const id = String(weaponId || "none").toLowerCase();
  if (seen.has(id)) return null;
  seen.add(id);
  const raw = DOC.weapons[id];
  if (!raw) {
    // Fall back to animPackForWeapon → synthetic entry
    const pack = animPackForWeapon(id) || "unarmed";
    return {
      label: id,
      animPack: pack,
      fallbackPack: null,
      liveRoles: {},
    };
  }
  if (raw.inheritsFrom) {
    const parent = resolveEntry(raw.inheritsFrom, seen);
    if (!parent) {
      return {
        label: raw.label || id,
        animPack: raw.animPack || "unarmed",
        fallbackPack: (raw.fallbackPack as string | null) ?? null,
        liveRoles: { ...(raw.liveRoles || {}) },
        liveWhenIncomplete: raw.liveWhenIncomplete as WeaponLiveDef["liveWhenIncomplete"],
        mixamoSources: raw.mixamoSources || [],
        skillSlots: raw.skillSlots || [],
      };
    }
    return {
      label: raw.label || parent.label,
      animPack: raw.animPack || parent.animPack,
      fallbackPack:
        raw.fallbackPack !== undefined
          ? (raw.fallbackPack as string | null)
          : parent.fallbackPack,
      liveRoles: { ...parent.liveRoles, ...(raw.liveRoles || {}) },
      liveWhenIncomplete:
        (raw.liveWhenIncomplete as WeaponLiveDef["liveWhenIncomplete"]) ||
        parent.liveWhenIncomplete,
      mixamoSources: raw.mixamoSources || parent.mixamoSources || [],
      skillSlots: raw.skillSlots || parent.skillSlots || [],
    };
  }
  return {
    label: raw.label || id,
    animPack: raw.animPack || "unarmed",
    fallbackPack: (raw.fallbackPack as string | null) ?? null,
    liveRoles: { ...(raw.liveRoles || {}) },
    liveWhenIncomplete: raw.liveWhenIncomplete as WeaponLiveDef["liveWhenIncomplete"],
    mixamoSources: raw.mixamoSources || [],
    skillSlots: raw.skillSlots || [],
  };
}

/** Full weapon live def (with inheritance). */
export function getWeaponLiveDef(weaponId: string | null | undefined): WeaponLiveDef {
  return (
    resolveEntry(String(weaponId || "none").toLowerCase()) || {
      label: "Unarmed",
      animPack: "unarmed",
      fallbackPack: null,
      liveRoles: {},
    }
  );
}

/**
 * Which anim pack is live when this weapon is equipped.
 * Prefer SSOT map; fall back to animPackForWeapon().
 */
export function liveAnimPackForWeapon(weaponId: string | null | undefined): AnimPack {
  const def = getWeaponLiveDef(weaponId);
  const pack = def.animPack as AnimPack;
  return pack || animPackForWeapon(weaponId) || "unarmed";
}

/**
 * Ordered bake rels that should load for this weapon (roles + optional incomplete fallbacks).
 * Hosts call this when equipping to know the live set.
 */
export function liveBakeRelsForWeapon(
  weaponId: string | null | undefined,
  opts?: { includeTraversal?: boolean; preferIncompleteFallback?: boolean },
): { role: string; bakeRel: string; preferred: boolean }[] {
  const def = getWeaponLiveDef(weaponId);
  const out: { role: string; bakeRel: string; preferred: boolean }[] = [];
  const seen = new Set<string>();

  const add = (role: string, bakeRel: string, preferred: boolean) => {
    const key = `${role}:${bakeRel}`;
    if (seen.has(key) || !bakeRel) return;
    seen.add(key);
    out.push({ role, bakeRel, preferred });
  };

  for (const [role, rel] of Object.entries(def.liveRoles || {})) {
    add(role, rel, true);
  }
  if (opts?.preferIncompleteFallback !== false && def.liveWhenIncomplete) {
    for (const [role, rel] of Object.entries(def.liveWhenIncomplete)) {
      if (role === "note") continue;
      if (typeof rel === "string") add(role, rel, false);
    }
  }
  if (opts?.includeTraversal !== false && DOC.sharedTraversal?.roles) {
    for (const [role, rel] of Object.entries(DOC.sharedTraversal.roles)) {
      add(role, rel, true);
    }
  }
  return out;
}

/**
 * Best-practice pick for one role when equipping a weapon.
 * Prefer preferred bake; if `available` set is provided and preferred is absent,
 * use liveWhenIncomplete or leave preferred for the loader to try.
 */
export function pickLiveBakeRel(
  weaponId: string | null | undefined,
  role: string,
  available?: Set<string> | string[],
): { bakeRel: string; preferred: boolean; status: LiveRoleStatus } | null {
  const def = getWeaponLiveDef(weaponId);
  const preferred = def.liveRoles?.[role];
  const fallback =
    def.liveWhenIncomplete && typeof def.liveWhenIncomplete[role] === "string"
      ? (def.liveWhenIncomplete[role] as string)
      : null;
  const avail = available
    ? available instanceof Set
      ? available
      : new Set(available)
    : null;

  const has = (rel: string | null | undefined) => {
    if (!rel) return false;
    if (!avail) return true;
    return avail.has(rel) || avail.has(rel + ".json");
  };

  if (preferred && has(preferred)) {
    return { bakeRel: preferred, preferred: true, status: "ready" };
  }
  if (fallback && has(fallback)) {
    return { bakeRel: fallback, preferred: false, status: "fallback" };
  }
  if (preferred) {
    return {
      bakeRel: preferred,
      preferred: true,
      status: avail ? "missing" : "ready",
    };
  }
  if (fallback) {
    return { bakeRel: fallback, preferred: false, status: avail ? "missing" : "fallback" };
  }
  return null;
}

/** Human table: weapon → pack → primary bake rels (for HUD / docs / debug). */
export function weaponLiveSummary(): {
  weaponId: string;
  label: string;
  animPack: string;
  fallbackPack: string | null;
  roles: string[];
}[] {
  return Object.keys(DOC.weapons).map((weaponId) => {
    const def = getWeaponLiveDef(weaponId);
    return {
      weaponId,
      label: def.label,
      animPack: def.animPack,
      fallbackPack: def.fallbackPack,
      roles: Object.keys(def.liveRoles || {}),
    };
  });
}

export function sharedTraversalRoles(): Record<string, string> {
  return { ...(DOC.sharedTraversal?.roles || {}) };
}

export function weaponLivePolicy(): Record<string, unknown> {
  return { ...(DOC.policy || {}) };
}

export function listMappedWeaponIds(): string[] {
  return Object.keys(DOC.weapons);
}
